### PR TITLE
Fix shortcuts

### PR DESCRIPTION
**Pull request by grzegorzsn**
Changes:

1. Fixed incorrect matching problem
2. Provide explanation for comparing function

Please do not merge until we are sure that finally works correctly.

### CODE REVIEW

**Comment by wyhasany** [comment]
1. To save a little of time you could execute only once the same commands:
```
...
gsettings set org.gnome.desktop.wm.keybindings begin-resize "['<Super>F8']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super>F10']"
gsettings set org.gnome.desktop.wm.keybindings begin-move "['<Super>F7']"
gsettings set org.gnome.desktop.wm.keybindings begin-resize "['<Super>F8']"
...
```
(see first and fourth line)
2. Partial collisions seems to be harmful:
```
Original IntellIJ shortcut: control alt SPACE
org.gnome.desktop.wm.keybindings activate-window-menu ['<Alt>space']
Match was found at 55-67: '<ALT>SPACE'
```
That partial change will break shortcut to open menu Start/Applications.

All other changes LGTM

**Comment by wyhasany** [comment]
Please rebase over my changes

**Comment by wyhasany** [comment]
You can ignore second point. It doesn't affect elementary os. But still I think partial shortcuts collisions are vulnerable. Maybe we should add flag to remove them either?

**Comment by grzegorzsn** [comment]
I rebased the branch (be careful if you have my fork as a remote) and introduced changes you requested :)

Now partial conflicts are not checked by default, but one can turn it on using new flag.
Commands duplication is also resolved.

**Review by wyhasany — APPROVED** [review]
It looks like exactly as it should. Just well done :+1:

**Pull request merged**
